plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

def modVersion = project.mod_version
def targetMinecraftVersion = project.minecraft_version
def targetLoaderVersion = project.loader_version
def archiveBaseName = project.archives_base_name
def fabricApiVersion = project.fabric_api_version
def litematicaVersion = project.litematica_version
def malilibVersion = project.malilib_version

base {
    archivesName = archiveBaseName
}

repositories {
    maven {
        name = 'CurseMaven'
        url = 'https://www.cursemaven.com'
        content {
            includeGroup 'curse.maven'
        }
    }

    maven {
        name = 'Modrinth'
        url = 'https://api.modrinth.com/maven'
        content {
            includeGroup 'maven.modrinth'
        }
    }
    mavenCentral()
    google()
}

dependencies {

    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "maven.modrinth:litematica:${litematicaVersion}"
    implementation "maven.modrinth:malilib:${malilibVersion}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabricApiVersion}"
    testImplementation "org.junit.jupiter:junit-jupiter:5.10.2"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"
}

test {
    useJUnitPlatform()
}

processResources {
    inputs.property "version", modVersion
    inputs.property "minecraft_version", targetMinecraftVersion
    inputs.property "loader_version", targetLoaderVersion
    filteringCharset = "UTF-8"

    filesMatching("fabric.mod.json") {
        expand "version": modVersion,
                "minecraft_version": targetMinecraftVersion,
                "loader_version": targetLoaderVersion
    }
}

def targetJavaVersion = 25
tasks.withType(JavaCompile).configureEach {

    it.options.encoding = "UTF-8"
    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        it.options.release.set(targetJavaVersion)
    }
}

java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }

    withSourcesJar()
}

loom {
    runConfigs.named("client") {
        runDir("run")
    }
}

jar {
    from("LICENSE") {
        rename { "${it}_${archiveBaseName}"}
    }
}

publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = archiveBaseName
            from components.java
        }
    }

    repositories {

    }
}
