plugins {
    id 'fabric-loom' version '1.17.12'
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

def modVersion = project.mod_version
def targetMinecraftVersion = project.minecraft_version
def targetLoaderVersion = project.loader_version
def archiveBaseName = project.archives_base_name

base {
    archivesName = project.archives_base_name
}

repositories {
    maven {
        name = 'CurseMaven'
        url = 'https://www.cursemaven.com'
        content {
            includeGroup 'curse.maven'
        }
    }

    maven {
        name = 'Modrinth'
        url = 'https://api.modrinth.com/maven'
        content {
            includeGroup 'maven.modrinth'
        }
    }
    mavenCentral()
    google()
}

dependencies {

    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "maven.modrinth:litematica:${project.litematica_version}"
    modImplementation "maven.modrinth:malilib:${project.malilib_version}"
    modRuntimeOnly(modApi(fabricApi.module("fabric-api-base", project.fabric_api_version)))
    modRuntimeOnly(modApi(fabricApi.module("fabric-networking-api-v1", project.fabric_api_version)))
    modRuntimeOnly(modApi(fabricApi.module("fabric-resource-loader-v0", project.fabric_api_version)))
    testImplementation "org.junit.jupiter:junit-jupiter:5.10.2"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"

}

test {
    useJUnitPlatform()
}

processResources {
    inputs.property "version", modVersion
    inputs.property "minecraft_version", targetMinecraftVersion
    inputs.property "loader_version", targetLoaderVersion
    filteringCharset = "UTF-8"

    filesMatching("fabric.mod.json") {
        expand "version": modVersion,
                "minecraft_version": targetMinecraftVersion,
                "loader_version": targetLoaderVersion
    }
}

def targetJavaVersion = 21
tasks.withType(JavaCompile).configureEach {

    it.options.encoding = "UTF-8"
    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        it.options.release.set(targetJavaVersion)
    }
}

java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }

    withSourcesJar()
}

loom{
    runConfigs.named("client") {
        runDir("run")
    }
}

jar {
    from("LICENSE") {
        rename { "${it}_${archiveBaseName}"}
    }
}

publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = project.archives_base_name
            from components.java
        }
    }

    repositories {

    }
}
