minecraft_version=1.21.11
yarn_mappings=1.21.11+build.6
loader_version=0.18.4

mod_version=0.6.6-1.21.11
maven_group=org.uiop
archives_base_name=EasyPlaceFix
fabric_api_version=0.141.6+1.21.11
litematica_version=0.26.12
malilib_version=0.27.16

org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.jvmargs=-Xmx4g

