# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1.2
loader_version=0.19.3
loom_version=1.17.12

# Mod Properties
mod_version=0.6.5
maven_group=org.uiop
archives_base_name=EasyPlaceFix
fabric_api_version_26_1_2=0.153.0+26.1.2
fabric_api_version_26_2=0.153.0+26.2
litematica_version_26_1_2=0.27.10
litematica_version_26_2=0.28.4
malilib_version_26_1_2=0.28.9
malilib_version_26_2=0.29.3

org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.jvmargs=-Xmx4g
